version: "3.9"
services:
    rabbitmq:
        image: "rabbitmq:3-management"
        deploy:
            replicas: 1
        ports:
            - "15672:15672"
            - "5672:5672"
        hostname: "rabbitmqhn"
    mssqldb:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "MightyPassword2022!"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
    mp-machines:
        build: ./services/MP.Machines
        ports:
            - "8000:80"
        depends_on:
            - mssqldb
            - rabbitmq
    mach-par-sim:
        build: ./simulators/MachineParameters
        ports:
            - "8081:80"
        depends_on:
            - mssqldb
            - mp-machines
            - rabbitmq
