version: "3.9"
services:
    mssqldb:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "MightyPassword2022!"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
    mp-machines:
        build: ./services/MP.Machines
        ports:
            - "8000:80"
        depends_on:
            - mssqldb
    mach-par-sim:
        build: ./simulators/MachineParameters
        ports:
            - "8081:80"
        depends_on:
            - mssqldb
            - mp-machines
