version: "3.9"
services:
    web:
        build: ./services/MP.Machines/Machines.Api
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "Samolocik123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"

