version: "3.9"
services:
    web:
        build: ./services/MP.Machines
        ports:
            - "8000:80"
        depends_on:
            - mssqldb
    mssqldb:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "MightyPassword2022!"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
